import '../styles/globals.scss';
import Footer from './components/Footer';
import Nav from './components/Nav';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
export const metadata = {
  title: 'home cinema',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav></Nav>
        
        
        {children}

        
        <Footer/>
        
        </body>
    </html>
  )
}
