import '../styles/globals.scss'
import Footer from './components/Footer'
import Nav from './components/Nav'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav></Nav>
        
        
        {children}

        
        <Footer/>
        
        </body>
    </html>
  )
}
